### PR TITLE
Port btest to D

### PR DESCRIPTION
**Pull request by eatonphil**
Some local numbers testing against bsdscheme's suite (btest is crsytal-btest, dbtest is d-btest):

```bash
$ { time btest ; } 2> time.text; cat time.txt
btest  0.47s user 0.47s system 95% cpu 0.990 total
$ { time dbtest ; } 2> dtime.text; cat dtime.txt
dbtest  0.15s user 0.11s system 74% cpu 0.356 total
```

Over 66% improvement on total time in this suite. The code is also ~300 lines whereas crystal was ~400 lines. Now there is no pretty formatting so that might account for some many things.

Pieces I know I'm missing in this initial PR:

* [ ] Pretty printing (color escapes)
* [ ] Command line flags
* [x] Runner setup https://github.com/briansteffens/bshift/blob/master/btest.yaml#L5

### CODE REVIEW

**Comment by eatonphil** [comment]
Example of this in use in BSDScheme https://github.com/eatonphil/bsdscheme/pull/45

**Comment by faustinoaq** [comment]
Hi @eatonphil I have seen neither D or Crystal are using compiler optimization, crystal is a bit slow on normal build mode because it avoid a lot of performance checks in aims to compile faster, if really want to test performance please use `-b release` for D and `--release` for Crystal.

Also see my PR https://github.com/briansteffens/btest/pull/4, I'm not an expert, so I think my PR would be improved even more :wink:

**Comment by eatonphil** [comment]
I set the default to not parallelize runners because I don't synchronize on runner output... all the output got mixed up randomly. So this way all output is under the appropriate runner text group. You can explicitly enable parallel runners in the btest.yaml. In the future we may want to collect/synchronize output (for other reasons) such that this wouldn't be an issue.

**Comment by briansteffens** [comment]
Merged on the command line :tada:

**Pull request closed without merging**
